sub init()
    m.top.backgroundColor = "#000000"
    m.top.backgroundUri = ""

    m.global.addFields({
        "isLoggedIn": false
    })

    m.router@.addRoutes([
        { pattern: "/", component: "WelcomeScreen", isRoot: true },
        { pattern: "/shows", component: "CatalogScreen", isRoot: true, canActivate: ["AuthManager"] },
        { pattern: "/movies", component: "CatalogScreen", isRoot: true },
        { pattern: "/details/:type/:id", component: "DetailsScreen" },
        { pattern: "/details/:type/:id/cast", component: "CastDetailsScreen" },
        { pattern: "/:screenName", component: "DefaultScreen" }
    ])

    ' Read the sample data from the file. You normally wouldn't want to do this in a real app.
    m.global.update(ParseJSON(ReadAsciiFile("pkg:/assets/sampleData.json")), true)

    m.router@.navigateTo("/?firstLoad=true", {})
end sub

function onKeyEvent(key = "" as String, press = false as Boolean) as Boolean
    return true
end function