sub init()
    m.buttonGroup.observeField("buttonSelected", "onButtonPress")
    m.buttonGroup.buttons = ["Go to Shows Catalog", "Go to Movies Catalog", "Test Params Change", "Test Hash Change"]
end sub

function onScreenOpen(context = Invalid as Dynamic) as Dynamic
    m.buttonGroup.setFocus(true)
    return promises.resolve(Invalid)
end function

function onRouteUpdate(oldParams = {} as Object, newParams = {} as Object) as Dynamic
    return promises.resolve(Invalid)
end function

function beforeScreenClose(context = Invalid as Dynamic) as Dynamic
    m.buttonGroup.unobserveField("buttonSelected")
    return promises.resolve(Invalid)
end function

sub onButtonPress(event as Object)
    button = event.getData()
    if button = 0 then
        Router.navigateTo("/shows")
    else if button = 1 then
        Router.navigateTo("/movies")
    else if button = 2 then
        Router.navigateTo("/?firstLoad=false", { allowReuse: true })
    else if button = 3 then
        Router.navigateTo("/#hello")
    end if
end sub

function onScreenResume(context = Invalid as Dynamic) as Dynamic
    m.buttonGroup.setFocus(true)
    return promises.resolve(Invalid)
end function