sub init()
    m.label = m.top.findNode("label")
    m.buttonGroup = m.top.findNode("buttonGroup")
    m.buttonGroup.buttons = ["Login", "Shows (Protected)", "Movies (Protected)", "Movie Details", "Movie Cast"]
    m.buttonGroup.observeField("buttonSelected", "onButtonPress")
end sub

function beforeViewClose(params = Invalid as Dynamic) as Dynamic
    m.buttonGroup.unobserveField("buttonSelected")
    return promises.resolve(true)
end function

function handleFocus(data as Object) as Boolean
    if data.routerHasFocus then
        return m.buttonGroup.setFocus(true)
    end if

    return false
end function

sub onButtonPress(event as Object)
    button = event.getData()
    navigateTo = Invalid
    if button = 0 then
        m.global.AuthManager.isLoggedIn = true
        return
    else if button = 1 then
        navigateTo = "/shows"
    else if button = 2 then
        navigateTo = "/movies"
    else if button = 3 then
        navigateTo = "/movie/1/details"
    else if button = 4 then
        navigateTo = "/movie/1/cast"
    end if

    if navigateTo <> Invalid then
        rokuRouter.navigateTo(navigateTo)
    end if
end sub
