function canActivate(currentRequest = {} as Object) as Boolean
    if m.global.isLoggedIn then
        return true
    end if

    dialog = createObject("roSGNode", "Dialog")
    dialog.title = "You must be logged in"
    dialog.optionsDialog = true
    dialog.message = "Press * To Dismiss"
    m.top.getScene().dialog = dialog

    currentRequest.router@.navigateTo("/?needToLogin=true", {})
    return false
end function